apiVersion: v1
kind: Service
metadata:
  name: ellis-web
  labels:
    name: web
    app: demo  
spec: 
  type: NodePort
  ports: 
    - name: http
      port: 8080
      targetPort: http
  selector: 
    role: web
