apiVersion: apps/v1
kind: Deployment
metadata:
  name: ellis-web
  labels:
    name: ellis
    app: demo
spec:
  selector:
    matchLabels:
      role: web
  template:
    metadata:
      labels:
        role: web
    spec:
      containers:
      - image: ellisp97/webserver
        name: webserver
        ports:
        - containerPort: 5000
          name: http
        - containerPort: 5556
          name: metrics
        env:
        - name: DB_USER
          value: user1
        - name: DB_PASS
          value: {{ .Values.db.password }}
        - name: DB_SERVER
          value: mysql
        - name: DB_DATABASE
          value: AZUREDB

