apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    name: mysql
    app: ellis-db
spec:
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  selector:
    app: ellis
    role: db


